import { auth, db, collection, addDoc, getDocs, serverTimestamp, onAuthStateChanged, doc, getDoc, setDoc, query, where } from "./firebase-service.js";
import { getCartForCheckout, getCartTotalForCheckout, clearCartAfterOrder } from "./store.js";
const form=document.getElementById("checkoutForm"),customerName=document.getElementById("customerName"),customerPhone=document.getElementById("customerPhone"),fulfillment=document.getElementById("fulfillment"),deliveryZone=document.getElementById("deliveryZone"),deliveryAddress=document.getElementById("deliveryAddress"),orderNote=document.getElementById("orderNote");let signedInUser=null,zones=[],selectedZone=null;
const money=a=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(a||0));
function hydrateLocalCustomer(){try{const d=JSON.parse(localStorage.getItem("biserryCustomerDetails")||"null");if(!d)return;customerName.value=d.name||"";customerPhone.value=d.phone||"";deliveryAddress.value=d.address||"";}catch{}}
async function hydrateAccount(user){if(!user)return;try{const snap=await getDoc(doc(db,"customers",user.uid));if(!snap.exists())return;const d=snap.data();customerName.value=d.name||customerName.value||"";customerPhone.value=d.phone||customerPhone.value||"";deliveryAddress.value=d.defaultAddress||deliveryAddress.value||"";const note=document.getElementById("checkoutAccountNote");if(note)note.textContent=`Signed in as ${user.email}. This order will appear in My Biserry.`;}catch(e){console.warn(e)}}
async function loadZones(){const snap=await getDocs(query(collection(db,"delivery_zones"),where("isActive","==",true)));zones=snap.docs.map(d=>({id:d.id,...d.data()}));deliveryZone.innerHTML='<option value="">Select delivery region / zone</option>'+zones.map(z=>`<option value="${z.id}">${z.zone} — ${money(z.fee)}</option>`).join("");}
async function loadPaymentSettings(){try{const s=await getDoc(doc(db,"app_config","payment")),el=document.getElementById("checkoutBankDetails");if(!s.exists()){el.textContent="Bank details will be shown on the payment page after your order is created.";return;}const d=s.data();el.innerHTML=`<strong>Bank Transfer Only</strong><br>${d.bankName||""} • ${d.accountName||""}<br><strong>${d.accountNumber||""}</strong><br><small>You will upload proof after placing the order.</small>`;}catch{}}
function recalc(){selectedZone=zones.find(z=>z.id===deliveryZone.value)||null;const productTotal=getCartTotalForCheckout(),fee=fulfillment.value==="Delivery"?Number(selectedZone?.fee||0):0,total=productTotal+fee;document.getElementById("checkoutProductTotal").textContent=money(productTotal);document.getElementById("checkoutDeliveryFee").textContent=money(fee);document.getElementById("checkoutTotal").textContent=money(total);return {productTotal,fee,total};}
function syncFulfillment(){const delivery=fulfillment.value==="Delivery";deliveryAddress.required=delivery;deliveryZone.required=delivery;deliveryAddress.style.display=delivery?"block":"none";deliveryZone.style.display=delivery?"block":"none";if(!delivery){deliveryAddress.value="";deliveryZone.value="";}recalc();}
hydrateLocalCustomer();loadZones().then(recalc).catch(console.warn);loadPaymentSettings();syncFulfillment();fulfillment?.addEventListener("change",syncFulfillment);deliveryZone?.addEventListener("change",recalc);onAuthStateChanged(auth,user=>{signedInUser=user||null;if(user)hydrateAccount(user)});
form?.addEventListener("submit",async event=>{event.preventDefault();const cart=getCartForCheckout();if(!cart.length)return alert("Your cart is empty.");if(fulfillment.value==="Delivery"&&!selectedZone)return alert("Please select your delivery region.");const submit=form.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent="Placing order…";const totals=recalc(),zone=fulfillment.value==="Delivery"?selectedZone:null;const order={customerUid:signedInUser?.uid||null,customerEmail:signedInUser?.email||"",customerName:customerName.value.trim(),customerPhone:customerPhone.value.trim(),fulfillment:fulfillment.value,deliveryZoneId:zone?.id||null,deliveryZone:zone?.zone||"",deliveryAddress:deliveryAddress.value.trim(),deliveryFee:Number(zone?.fee||0),commissionPercent:Number(zone?.commissionPercent||0),biserryCommission:Number(zone?.biserryCommission||0),riderEarning:Number(zone?.riderEarning||0),paymentMethod:"Bank Transfer",orderNote:orderNote.value.trim(),items:cart,productTotal:totals.productTotal,total:totals.total,orderStatus:"Pending",paymentStatus:"Unpaid",deliveryReleaseStatus:"Locked",dispatchStatus:fulfillment.value==="Delivery"?"Not Requested":"Not Required",createdAt:serverTimestamp(),updatedAt:serverTimestamp()};try{const orderRef=await addDoc(collection(db,"orders"),order);await setDoc(doc(db,"orderTracking",orderRef.id),{orderStatus:order.orderStatus,paymentStatus:order.paymentStatus,deliveryReleaseStatus:order.deliveryReleaseStatus,dispatchStatus:order.dispatchStatus,fulfillment:order.fulfillment,total:order.total,deliveryZoneId:order.deliveryZoneId,deliveryZone:order.deliveryZone,deliveryFee:order.deliveryFee,commissionPercent:order.commissionPercent,biserryCommission:order.biserryCommission,riderEarning:order.riderEarning,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});localStorage.setItem("biserryCustomerDetails",JSON.stringify({name:order.customerName,phone:order.customerPhone,address:order.deliveryAddress}));localStorage.setItem("biserryLastOrder",JSON.stringify({orderId:orderRef.id,customerUid:order.customerUid,customerName:order.customerName,customerPhone:order.customerPhone,deliveryAddress:order.deliveryAddress,deliveryZoneId:order.deliveryZoneId,deliveryZone:order.deliveryZone,deliveryFee:order.deliveryFee,biserryCommission:order.biserryCommission,riderEarning:order.riderEarning,commissionPercent:order.commissionPercent,fulfillment:order.fulfillment,total:order.total,items:cart}));clearCartAfterOrder();location.href=`order-success.html?order=${encodeURIComponent(orderRef.id)}`;}catch(error){alert("Order failed: "+error.message);submit.disabled=false;submit.textContent="Place Order";}});
