import { auth, db, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, onAuthStateChanged, collection, getDocs, query, where, limit, doc, getDoc, setDoc, serverTimestamp } from "./firebase-service.js";
const authCard=document.getElementById("accountAuthCard"),profile=document.getElementById("accountProfile"),loginForm=document.getElementById("customerLoginForm"),registerForm=document.getElementById("customerRegisterForm"),ordersEl=document.getElementById("customerOrders");
const money=v=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v||0));
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function showRegister(on){loginForm.classList.toggle("hidden",on);registerForm.classList.toggle("hidden",!on)}
document.getElementById("showAccountLogin")?.addEventListener("click",()=>showRegister(false));document.getElementById("showAccountRegister")?.addEventListener("click",()=>showRegister(true));
loginForm?.addEventListener("submit",async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,document.getElementById("customerLoginEmail").value.trim().toLowerCase(),document.getElementById("customerLoginPassword").value)}catch(err){alert("Sign in failed: "+err.message)}});
registerForm?.addEventListener("submit",async e=>{e.preventDefault();try{const cred=await createUserWithEmailAndPassword(auth,document.getElementById("customerRegisterEmail").value.trim().toLowerCase(),document.getElementById("customerRegisterPassword").value);await setDoc(doc(db,"customers",cred.user.uid),{name:document.getElementById("customerRegisterName").value.trim(),phone:document.getElementById("customerRegisterPhone").value.trim(),email:cred.user.email,defaultAddress:"",role:"customer",createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch(err){alert("Account creation failed: "+err.message)}});
document.getElementById("customerSignOutBtn")?.addEventListener("click",()=>signOut(auth));
async function loadCustomer(user){const snap=await getDoc(doc(db,"customers",user.uid));const d=snap.exists()?snap.data():{};document.getElementById("customerProfileName").textContent=d.name||"My Biserry";document.getElementById("customerProfileEmail").textContent=user.email||"";document.getElementById("profileName").value=d.name||"";document.getElementById("profilePhone").value=d.phone||"";document.getElementById("profileAddress").value=d.defaultAddress||"";return d}
document.getElementById("customerProfileForm")?.addEventListener("submit",async e=>{e.preventDefault();const user=auth.currentUser;if(!user)return;await setDoc(doc(db,"customers",user.uid),{name:document.getElementById("profileName").value.trim(),phone:document.getElementById("profilePhone").value.trim(),email:user.email,defaultAddress:document.getElementById("profileAddress").value.trim(),role:"customer",updatedAt:serverTimestamp()},{merge:true});alert("Delivery details saved.");await loadCustomer(user)});
function reorder(order){const items=(order.items||[]).map(i=>({...i,quantity:Number(i.quantity||1)}));localStorage.setItem("biserryCart",JSON.stringify(items));location.href="cart.html"}
window.buyOrderAgain=id=>{const order=window.__biserryOrders?.find(x=>x.id===id);if(order)reorder(order)};
async function loadOrders(user){ordersEl.innerHTML='<div class="emptyState">Loading your orders…</div>';const snap=await getDocs(query(collection(db,"orders"),where("customerUid","==",user.uid),limit(30)));const list=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));window.__biserryOrders=list;document.getElementById("accountOrderCount").textContent=`${list.length} order${list.length===1?"":"s"}`;ordersEl.innerHTML=list.length?list.map(o=>`<article class="accountOrderCard"><div><span class="sectionLabel">${esc(o.orderStatus||"Pending")}</span><h4>Order ${esc(o.id)}</h4><p>${(o.items||[]).slice(0,3).map(i=>esc(i.name)).join(" • ")}${(o.items||[]).length>3?" + more":""}</p></div><div class="accountOrderActions"><strong>${money(o.total)}</strong><button class="btn small" type="button" onclick="buyOrderAgain('${o.id}')">Buy Again</button><a class="btn outline small" href="track-order.html?order=${encodeURIComponent(o.id)}">Track</a></div></article>`).join(""):'<div class="emptyState">No account-linked orders yet. Your next signed-in checkout will appear here.</div>'}
onAuthStateChanged(auth,async user=>{if(!user){authCard.classList.remove("hidden");profile.classList.add("hidden");return}authCard.classList.add("hidden");profile.classList.remove("hidden");await loadCustomer(user);await loadOrders(user)});
