import { auth, db, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, onAuthStateChanged, collection, getDocs, query, where, limit, doc, getDoc, setDoc, serverTimestamp } from "./firebase-service.js";
const authCard=document.getElementById("accountAuthCard"),profile=document.getElementById("accountProfile"),loginForm=document.getElementById("customerLoginForm"),registerForm=document.getElementById("customerRegisterForm"),ordersEl=document.getElementById("customerOrders"),listsEl=document.getElementById("customerShoppingLists");
let customerData={};
const money=v=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v||0));
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function showRegister(on){loginForm.classList.toggle("hidden",on);registerForm.classList.toggle("hidden",!on)}
document.getElementById("showAccountLogin")?.addEventListener("click",()=>showRegister(false));document.getElementById("showAccountRegister")?.addEventListener("click",()=>showRegister(true));
loginForm?.addEventListener("submit",async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,document.getElementById("customerLoginEmail").value.trim().toLowerCase(),document.getElementById("customerLoginPassword").value)}catch(err){alert("Sign in failed: "+err.message)}});
registerForm?.addEventListener("submit",async e=>{e.preventDefault();try{const cred=await createUserWithEmailAndPassword(auth,document.getElementById("customerRegisterEmail").value.trim().toLowerCase(),document.getElementById("customerRegisterPassword").value);await setDoc(doc(db,"customers",cred.user.uid),{name:document.getElementById("customerRegisterName").value.trim(),phone:document.getElementById("customerRegisterPhone").value.trim(),email:cred.user.email,defaultAddress:"",role:"customer",createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch(err){alert("Account creation failed: "+err.message)}});
document.getElementById("customerSignOutBtn")?.addEventListener("click",()=>signOut(auth));
async function loadCustomer(user){const snap=await getDoc(doc(db,"customers",user.uid));const d=snap.exists()?snap.data():{};customerData=d;document.getElementById("customerProfileName").textContent=d.name||"My Biserry";document.getElementById("customerProfileEmail").textContent=user.email||"";document.getElementById("profileName").value=d.name||"";document.getElementById("profilePhone").value=d.phone||"";document.getElementById("profileAddress").value=d.defaultAddress||"";return d}
document.getElementById("customerProfileForm")?.addEventListener("submit",async e=>{e.preventDefault();const user=auth.currentUser;if(!user)return;await setDoc(doc(db,"customers",user.uid),{name:document.getElementById("profileName").value.trim(),phone:document.getElementById("profilePhone").value.trim(),email:user.email,defaultAddress:document.getElementById("profileAddress").value.trim(),role:"customer",updatedAt:serverTimestamp()},{merge:true});alert("Delivery details saved.");await loadCustomer(user)});

function renderShoppingLists(){if(!listsEl)return;const lists=Array.isArray(customerData.savedLists)?customerData.savedLists:[];listsEl.innerHTML=lists.length?lists.map((l,i)=>`<article class="accountOrderCard"><div><span class="sectionLabel">Saved list</span><h4>${esc(l.name||`List ${i+1}`)}</h4><p>${(l.items||[]).slice(0,4).map(x=>esc(x.name)).join(" • ")}${(l.items||[]).length>4?" + more":""}</p></div><div class="accountOrderActions"><button class="btn small" type="button" onclick="loadSavedList(${i})">Add to Cart</button><button class="btn outline small" type="button" onclick="deleteSavedList(${i})">Delete</button></div></article>`).join(""):'<div class="emptyState">No saved shopping list yet.</div>'}
async function persistLists(){const u=auth.currentUser;if(!u)return;await setDoc(doc(db,"customers",u.uid),{savedLists:customerData.savedLists||[],updatedAt:serverTimestamp()},{merge:true});renderShoppingLists()}
window.loadSavedList=i=>{const l=(customerData.savedLists||[])[i];if(!l)return;localStorage.setItem("biserryCart",JSON.stringify(l.items||[]));location.href="cart.html"};
window.deleteSavedList=async i=>{if(!confirm("Delete this saved shopping list?"))return;customerData.savedLists=(customerData.savedLists||[]).filter((_,x)=>x!==i);await persistLists()};
document.getElementById("saveCurrentCartListBtn")?.addEventListener("click",async()=>{const cart=JSON.parse(localStorage.getItem("biserryCart")||"[]");if(!cart.length)return alert("Your cart is empty. Add products first, then save the cart as a list.");const name=prompt("Name this shopping list","Monthly Groceries");if(!name)return;customerData.savedLists=[...(customerData.savedLists||[]),{name:name.trim(),items:cart,createdAt:new Date().toISOString()}].slice(-20);await persistLists();alert("Shopping list saved.")});
function reorder(order){const items=(order.items||[]).map(i=>({...i,quantity:Number(i.quantity||1)}));localStorage.setItem("biserryCart",JSON.stringify(items));location.href="cart.html"}
window.buyOrderAgain=id=>{const order=window.__biserryOrders?.find(x=>x.id===id);if(order)reorder(order)};
async function loadOrders(user){ordersEl.innerHTML='<div class="emptyState">Loading your orders…</div>';const snap=await getDocs(query(collection(db,"orders"),where("customerUid","==",user.uid),limit(30)));const list=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));window.__biserryOrders=list;document.getElementById("accountOrderCount").textContent=`${list.length} order${list.length===1?"":"s"}`;ordersEl.innerHTML=list.length?list.map(o=>`<article class="accountOrderCard"><div><span class="sectionLabel">${esc(o.orderStatus||"Pending")}</span><h4>Order ${esc(o.id)}</h4><p>${(o.items||[]).slice(0,3).map(i=>esc(i.name)).join(" • ")}${(o.items||[]).length>3?" + more":""}</p></div><div class="accountOrderActions"><strong>${money(o.total)}</strong><button class="btn small" type="button" onclick="buyOrderAgain('${o.id}')">Buy Again</button><a class="btn outline small" href="track-order.html?order=${encodeURIComponent(o.id)}">Track</a></div></article>`).join(""):'<div class="emptyState">No account-linked orders yet. Your next signed-in checkout will appear here.</div>'}
onAuthStateChanged(auth,async user=>{if(!user){authCard.classList.remove("hidden");profile.classList.add("hidden");return}authCard.classList.add("hidden");profile.classList.remove("hidden");await loadCustomer(user);renderShoppingLists();await loadOrders(user)});

function localArray(key){try{return JSON.parse(localStorage.getItem(key)||"[]")||[]}catch{return[]}}
function renderLocalShoppingMemory(){
  const fav=document.getElementById("customerFavorites"),recent=document.getElementById("customerRecentlyViewed");
  const favoriteIds=localArray("biserryWishlist"), viewed=localArray("biserryRecentlyViewed");
  if(fav){const known=viewed.filter(x=>favoriteIds.map(String).includes(String(x.id)));fav.innerHTML=known.length?known.map(x=>`<article class="accountOrderCard"><div><h4>${esc(x.name||"Favorite product")}</h4><p>${money(x.price||0)} • ${esc(x.category||"Product")}</p></div><a class="btn small" href="shop.html">Shop</a></article>`).join(""):(favoriteIds.length?`<div class="emptyState">${favoriteIds.length} favorite product(s) saved. Open Shop to view them as the catalogue loads.</div>`:'<div class="emptyState">No favorites yet. Tap ♥ on products you buy often.</div>');}
  if(recent)recent.innerHTML=viewed.length?viewed.slice(0,8).map(x=>`<article class="accountOrderCard"><div><h4>${esc(x.name||"Product")}</h4><p>${money(x.price||0)} • ${esc(x.category||"")}</p></div><a class="btn outline small" href="shop.html">View</a></article>`).join(""):'<div class="emptyState">Products you open in the shop will appear here.</div>';
}
function renderReorderSuggestions(orders){const el=document.getElementById("customerReorderSuggestions");if(!el)return;const counts=new Map();(orders||[]).slice(0,8).forEach(o=>(o.items||[]).forEach(i=>{const k=String(i.productId||i.id||i.name);const old=counts.get(k)||{...i,count:0};old.count++;counts.set(k,old)}));const top=[...counts.values()].sort((a,b)=>b.count-a.count).slice(0,5);el.innerHTML=top.length?top.map(i=>`<article class="accountOrderCard"><div><h4>${esc(i.name||"Product")}</h4><p>Bought in ${i.count} recent order${i.count===1?"":"s"}</p></div><a class="btn small" href="shop.html">Restock</a></article>`).join(""):'<div class="emptyState">Reorder suggestions appear after you have order history.</div>'; }
renderLocalShoppingMemory();
