import { auth, db, onAuthStateChanged, collection, query, where, onSnapshot, addDoc, doc, setDoc, serverTimestamp } from "./firebase-service.js";

const grid=document.getElementById("dispatchGrid"), status=document.getElementById("dispatchStatus");
let currentUser=null;
function phoneDigits(v=""){return String(v).replace(/[^0-9]/g,"").replace(/^0/,"234");}
function lastOrder(){try{return JSON.parse(localStorage.getItem("biserryLastOrder")||"null");}catch{return null;}}
function requestMessage(d){const o=lastOrder();return encodeURIComponent(`Hello ${d.name||""}, I would like to request dispatch service for a Biserry Grocery order.${o?.orderId?`\nOrder: ${o.orderId}`:""}${o?.customerName?`\nCustomer: ${o.customerName}`:""}${o?.deliveryAddress?`\nDelivery address: ${o.deliveryAddress}`:""}\nPlease confirm your availability and delivery fee.`);}
window.requestBiserryDispatcher=async id=>{const d=window.__dispatchers?.find(x=>x.id===id),o=lastOrder();if(!currentUser){if(confirm("Sign in to request a dispatcher inside Biserry. Guest customers can still use WhatsApp or Call."))location.href="account.html";return;}if(!o?.orderId){alert("Place an order first, then request a dispatcher from this page.");return;}if(o.customerUid&&o.customerUid!==currentUser.uid){alert("This order belongs to a different signed-in account.");return;}try{const reqRef=await addDoc(collection(db,"dispatchRequests"),{orderId:o.orderId,customerUid:currentUser.uid,dispatcherId:d.id,dispatcherName:d.name||"Dispatcher",deliveryArea:o.deliveryAddress||"",status:"Offered",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await setDoc(doc(db,"orderTracking",o.orderId),{dispatchRequestId:reqRef.id,dispatchStatus:"Requested",updatedAt:serverTimestamp()},{merge:true});alert(`${d.name||"Dispatcher"} has received your Biserry delivery request.`);}catch(e){alert("Request failed: "+e.message)}};
function render(items){window.__dispatchers=items;status.style.display=items.length?"none":"block";status.textContent=items.length?"":"No dispatcher is currently available. This page updates automatically when a dispatcher comes online.";grid.innerHTML=items.map(d=>`<article class="dispatchCard"><span class="dispatchLive">● Available now</span><h3>${d.name||"Dispatcher"}</h3><div class="dispatchMeta"><div><strong>Area:</strong> ${d.serviceArea||"Contact dispatcher"}</div><div><strong>Vehicle:</strong> ${d.vehicleType||"Not specified"}</div><div><strong>Phone:</strong> ${d.phone||""}</div></div><div class="dispatchActions"><button class="btn" type="button" onclick="requestBiserryDispatcher('${d.id}')">Request in Biserry</button><a class="btn outline" href="https://wa.me/${phoneDigits(d.phone)}?text=${requestMessage(d)}" target="_blank">WhatsApp</a><a class="btn outline" href="tel:${d.phone||""}">Call</a></div></article>`).join("");}
onAuthStateChanged(auth,u=>currentUser=u||null);
try{const q=query(collection(db,"dispatchers"),where("isPublic","==",true));onSnapshot(q,snap=>render(snap.docs.map(d=>({id:d.id,...d.data()}))),err=>{status.style.display="block";status.textContent="Could not load dispatchers right now. Please try again.";console.warn(err);});}catch(e){status.style.display="block";status.textContent="Could not load dispatchers right now. Please try again.";console.warn(e);}
