import { db, doc, getDoc, setDoc, serverTimestamp } from "./firebase-service.js";
const params=new URLSearchParams(location.search),orderId=params.get("order")||(()=>{try{return JSON.parse(localStorage.getItem("biserryLastOrder")||"null")?.orderId||""}catch{return ""}})();
const bankBox=document.getElementById("paymentBankDetails"),title=document.getElementById("paymentOrderTitle"),pill=document.getElementById("paymentStatusPill"),form=document.getElementById("paymentProofForm"),submitted=document.getElementById("paymentSubmitted"),track=document.getElementById("paymentTrackLink"),receipt=document.getElementById("paymentReceipt"),receiptHelp=document.getElementById("receiptHelp");
const money=v=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v||0));
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let tracking=null,config=null;
async function boot(){if(!orderId){pill.textContent="Order ID required";bankBox.textContent="Open this page from your Biserry order confirmation or add ?order=YOUR_ORDER_ID.";form.classList.add("hidden");return;}track.href=`track-order.html?order=${encodeURIComponent(orderId)}`;title.textContent=`Order ${orderId}`;const [ts,cs]=await Promise.all([getDoc(doc(db,"orderTracking",orderId)),getDoc(doc(db,"app_config","payment"))]);if(!ts.exists()){pill.textContent="Order not found";form.classList.add("hidden");return;}tracking=ts.data();config=cs.exists()?cs.data():{};pill.textContent=tracking.paymentStatus||"Unpaid";bankBox.innerHTML=`<div class="trackMeta"><div><small>Amount</small><strong>${money(tracking.total)}</strong></div><div><small>Bank</small><strong>${esc(config.bankName||"Not configured")}</strong></div><div><small>Account Name</small><strong>${esc(config.accountName||"Not configured")}</strong></div><div><small>Account Number</small><strong style="font-size:1.3rem">${esc(config.accountNumber||"Not configured")}</strong></div></div>`;if(!config.cloudinaryCloudName||!config.cloudinaryUploadPreset){receipt.required=false;receiptHelp.innerHTML=`Receipt image upload is not configured yet. You can submit your transfer reference and then notify Biserry on WhatsApp. Admin can still verify manually.`;}else receipt.required=true;if(tracking.paymentStatus==="Paid"){form.classList.add("hidden");submitted.classList.remove("hidden");submitted.innerHTML=`<div class="emptyState"><strong>Payment confirmed ✓</strong><br>Your order is authorized for release. <a href="dispatch.html?order=${encodeURIComponent(orderId)}">Request / view dispatch</a>.</div>`;}}
async function uploadReceipt(file){if(!file)return "";if(!config?.cloudinaryCloudName||!config?.cloudinaryUploadPreset)throw new Error("Receipt image upload has not been configured by Biserry admin.");const fd=new FormData();fd.append("file",file);fd.append("upload_preset",config.cloudinaryUploadPreset);fd.append("folder","biserry-payment-receipts");const res=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(config.cloudinaryCloudName)}/image/upload`,{method:"POST",body:fd});if(!res.ok)throw new Error("Receipt upload failed.");const data=await res.json();return data.secure_url||"";}
form?.addEventListener("submit",async e=>{e.preventDefault();if(!tracking)return;const btn=document.getElementById("submitPaymentProof");btn.disabled=true;btn.textContent="Submitting…";try{let receiptUrl="";if(receipt.files?.[0])receiptUrl=await uploadReceipt(receipt.files[0]);const paymentReference=document.getElementById("paymentReference").value.trim();if(!receiptUrl&&!paymentReference)throw new Error("Add a transaction reference or upload your payment receipt.");await setDoc(doc(db,"paymentProofs",orderId),{orderId,amount:Number(tracking.total||0),paymentReference,receiptUrl,status:"Awaiting Verification",submittedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,"orderTracking",orderId),{paymentStatus:"Awaiting Verification",deliveryReleaseStatus:"Locked",updatedAt:serverTimestamp()},{merge:true});pill.textContent="Awaiting Verification";form.classList.add("hidden");submitted.classList.remove("hidden");const number=String(config?.adminWhatsApp||"2348100584211").replace(/\D/g,"");const msg=`Hello Biserry, I have submitted payment for order ${orderId}. Amount: ${money(tracking.total)}.${paymentReference?` Reference: ${paymentReference}.`:""}${receiptUrl?` Receipt: ${receiptUrl}`:""}`;submitted.innerHTML=`<div class="emptyState"><strong>Payment proof received.</strong><br>Biserry will verify your transfer. Delivery release remains locked until approval.<br><br><a class="btn" target="_blank" rel="noopener" href="https://wa.me/${number}?text=${encodeURIComponent(msg)}">Notify Biserry on WhatsApp</a> <a class="btn outline" href="track-order.html?order=${encodeURIComponent(orderId)}">Track Order</a></div>`;}catch(err){alert(err.message);btn.disabled=false;btn.textContent="I Have Made Payment";}});
boot().catch(e=>{console.warn(e);bankBox.textContent="Payment information is temporarily unavailable.";});
