import { db, collection, getDocs, query, orderBy } from "./firebase-service.js";
const fallbackProducts=[{id:"demo-1",name:"Premium Rice",category:"grains",price:75000,stock:20,imageUrl:"assets/rice.jpg",hasVariants:false},{id:"demo-2",name:"Toothpaste",category:"household",hasVariants:true,imageUrl:"assets/household.jpg",variants:[{id:"v1",name:"Colgate",price:2500,stock:20,imageUrl:"assets/household.jpg"},{id:"v2",name:"Close-Up",price:2300,stock:15,imageUrl:"assets/household.jpg"},{id:"v3",name:"Oral-B",price:2800,stock:10,imageUrl:"assets/household.jpg"}]},{id:"demo-3",name:"Vegetable Oil",category:"oil",price:48000,stock:10,imageUrl:"assets/vegetable-oil.jpg",hasVariants:false}];
let products=[],cart=[],selectedQuantities={},selectedVariants={},deliveryZones=[],selectedDeliveryFee=0,currentCategory="all";
const productGrid=document.getElementById("productGrid"),searchInput=document.getElementById("searchInput"),cartItems=document.getElementById("cartItems"),cartTotal=document.getElementById("cartTotal"),cartCount=document.getElementById("cartCount"),checkoutPreview=document.getElementById("checkoutPreview"),checkoutTotal=document.getElementById("checkoutTotal"),clearCartBtn=document.getElementById("clearCartBtn"),deliveryZoneSelect=document.getElementById("deliveryZone"),fulfillmentSelect=document.getElementById("fulfillment"),deliveryFeePreview=document.getElementById("deliveryFeePreview");
function formatNaira(amount){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(amount||0)}
async function loadProducts(){try{const q=query(collection(db,"products"),orderBy("createdAt","desc"));const snap=await getDocs(q);products=snap.docs.map(d=>({id:d.id,...d.data()}));if(!products.length)products=fallbackProducts}catch(e){console.warn(e.message);products=fallbackProducts}renderProducts()}
async function loadDeliveryZones(){try{const snap=await getDocs(collection(db,"delivery_zones"));deliveryZones=snap.docs.map(d=>({id:d.id,...d.data()}));if(!deliveryZones.length)throw new Error("empty")}catch{deliveryZones=[{zone:"Pickup",fee:0},{zone:"Wuse",fee:2000},{zone:"Garki",fee:2500},{zone:"Maitama",fee:3000}]} if(deliveryZoneSelect){deliveryZoneSelect.innerHTML='<option value="">Select Delivery Zone</option>'+deliveryZones.map(z=>`<option value="${z.zone}" data-fee="${z.fee}">${z.zone} — ${formatNaira(Number(z.fee))}</option>`).join("")}}
function getSelectedQuantity(id){return selectedQuantities[id]||1}function getSelectedVariant(p){if(!p.hasVariants)return null;const vid=selectedVariants[p.id]||p.variants?.[0]?.id;return p.variants?.find(v=>String(v.id)===String(vid))||p.variants?.[0]}
window.selectVariant=(pid,vid)=>{selectedVariants[pid]=vid;renderProducts()};window.increaseProductQty=id=>{const p=products.find(x=>String(x.id)===String(id));const v=getSelectedVariant(p);const stock=v?Number(v.stock||0):Number(p.stock||0);const q=getSelectedQuantity(id);if(q>=stock){alert("Selected quantity cannot exceed available stock.");return}selectedQuantities[id]=q+1;renderProducts()};window.decreaseProductQty=id=>{selectedQuantities[id]=Math.max(1,getSelectedQuantity(id)-1);renderProducts()};
function renderProducts(){const s=(searchInput?.value||"").toLowerCase();const filtered=products.filter(p=>(currentCategory==="all"||p.category===currentCategory)&&p.name.toLowerCase().includes(s));if(!filtered.length){productGrid.innerHTML='<div class="emptyState">No product found.</div>';return}productGrid.innerHTML=filtered.map(p=>{const v=getSelectedVariant(p),q=getSelectedQuantity(p.id),price=v?Number(v.price||0):Number(p.price||0),stock=v?Number(v.stock||0):Number(p.stock||0),img=v?.imageUrl||p.imageUrl||p.image||"assets/logo.png",stockClass=stock<=Number(p.lowStockThreshold||5)?"stockText low":"stockText";const variantHtml=p.hasVariants&&p.variants?.length?`<div class="variantBox"><label>Select Variety</label><select onchange="selectVariant('${p.id}', this.value)">${p.variants.map(x=>`<option value="${x.id}" ${v?.id===x.id?"selected":""}>${x.name} — ${formatNaira(Number(x.price||0))}</option>`).join("")}</select></div>`:"";return `<div class="card"><div class="productImage"><img src="${img}" alt="${p.name}"></div><div class="cardBody"><div class="productMeta"><h3>${p.name}</h3><span class="categoryTag">${p.hasVariants?"Varieties":p.category}</span></div>${variantHtml}<p class="price">${formatNaira(price)}</p><p class="${stockClass}">${stock>0?`Available Stock: ${stock}`:"Out of Stock"}</p><div class="quantityRow"><button class="qtyBtn" onclick="decreaseProductQty('${p.id}')">−</button><div class="qtyDisplay">${q}</div><button class="qtyBtn" onclick="increaseProductQty('${p.id}')">+</button></div><button class="btn addBtn" onclick="addToCart('${p.id}')" ${stock<=0?"disabled":""}>${stock<=0?"Out of Stock":`Add ${q} to Cart`}</button></div></div>`}).join("")}
window.addToCart=id=>{const p=products.find(x=>String(x.id)===String(id)),v=getSelectedVariant(p),q=getSelectedQuantity(id),cartId=v?`${p.id}__${v.id}`:p.id,price=v?Number(v.price||0):Number(p.price||0),stock=v?Number(v.stock||0):Number(p.stock||0),display=v?`${p.name} - ${v.name}`:p.name;const existing=cart.find(i=>String(i.cartId)===String(cartId));if(existing){if(existing.quantity+q>stock){alert("Cart quantity cannot exceed available stock.");return}existing.quantity+=q}else cart.push({cartId,productId:p.id,variantId:v?.id||null,name:display,baseProductName:p.name,variantName:v?.name||null,category:p.category,price,stock,imageUrl:v?.imageUrl||p.imageUrl||"assets/logo.png",quantity:q});selectedQuantities[id]=1;renderProducts();renderCart();document.getElementById("cart").scrollIntoView({behavior:"smooth"})};
window.increaseCartQty=cid=>{const item=cart.find(i=>String(i.cartId)===String(cid));if(item.quantity>=Number(item.stock||0)){alert("Quantity cannot exceed available stock.");return}item.quantity++;renderCart()};window.decreaseCartQty=cid=>{const item=cart.find(i=>String(i.cartId)===String(cid));if(!item)return;item.quantity--;if(item.quantity<=0)cart=cart.filter(i=>String(i.cartId)!==String(cid));renderCart()};window.removeFromCart=cid=>{cart=cart.filter(i=>String(i.cartId)!==String(cid));renderCart()};
function getCartSubtotal(){return cart.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||1),0)}function getCartTotal(){return getCartSubtotal()+selectedDeliveryFee}function getCartCount(){return cart.reduce((s,i)=>s+Number(i.quantity||1),0)}function updateDeliveryFee(){if(fulfillmentSelect?.value==="Pickup"){selectedDeliveryFee=0;if(deliveryZoneSelect)deliveryZoneSelect.value="Pickup"}else{const opt=deliveryZoneSelect?.selectedOptions?.[0];selectedDeliveryFee=Number(opt?.dataset?.fee||0)}renderCart()}
function renderCart(){if(!cart.length){cartItems.innerHTML='<div class="emptyState">Your cart is empty. Select groceries from the shop section above.</div>';checkoutPreview.innerHTML='<div class="emptyState">No item selected yet.</div>';cartTotal.textContent=formatNaira(0);checkoutTotal.textContent=formatNaira(0);cartCount.textContent="0";if(deliveryFeePreview)deliveryFeePreview.textContent=formatNaira(selectedDeliveryFee);return}cartItems.innerHTML=cart.map(i=>`<div class="cartItem"><div><strong>${i.name}</strong><br><span>${formatNaira(i.price)} x ${i.quantity}</span><br><span>Subtotal: ${formatNaira(i.price*i.quantity)}</span></div><div class="cartControls"><button onclick="decreaseCartQty('${i.cartId}')">−</button><span>${i.quantity}</span><button onclick="increaseCartQty('${i.cartId}')">+</button><button class="removeBtn" onclick="removeFromCart('${i.cartId}')">×</button></div></div>`).join("");checkoutPreview.innerHTML=cart.map(i=>`<div class="previewItem"><div><strong>${i.name}</strong><br><span>${formatNaira(i.price)} x ${i.quantity}</span></div><strong>${formatNaira(i.price*i.quantity)}</strong></div>`).join("");cartTotal.textContent=formatNaira(getCartTotal());checkoutTotal.textContent=formatNaira(getCartTotal());cartCount.textContent=getCartCount();if(deliveryFeePreview)deliveryFeePreview.textContent=formatNaira(selectedDeliveryFee)}
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentCategory=b.dataset.category;renderProducts()}));searchInput?.addEventListener("input",renderProducts);deliveryZoneSelect?.addEventListener("change",updateDeliveryFee);fulfillmentSelect?.addEventListener("change",updateDeliveryFee);clearCartBtn?.addEventListener("click",()=>{cart=[];renderCart()});
export function getCartForCheckout(){return cart}export function getCartSubtotalForCheckout(){return getCartSubtotal()}export function getDeliveryFeeForCheckout(){return selectedDeliveryFee}export function getDeliveryZoneForCheckout(){return deliveryZoneSelect?.value||""}export function getCartTotalForCheckout(){return getCartTotal()}export function clearCartAfterOrder(){cart=[];renderCart()}
await loadDeliveryZones();await loadProducts();renderCart();

