import { auth, db, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, onAuthStateChanged, collection, addDoc, getDocs, getDoc, query, where, onSnapshot, doc, updateDoc, setDoc, serverTimestamp } from "../js/firebase-service.js";
const authCard=document.getElementById("authCard"), profileCard=document.getElementById("profileCard"), jobsCard=document.getElementById("dispatcherJobsCard"), loginForm=document.getElementById("loginForm"), registerForm=document.getElementById("registerForm");
let profile=null,unsubscribeJobs=null;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toggleForms(register=false){loginForm.classList.toggle("hidden",register);registerForm.classList.toggle("hidden",!register);}
async function findProfile(uid){const q=query(collection(db,"dispatchers"),where("authUid","==",uid));const snap=await getDocs(q);return snap.empty?null:{id:snap.docs[0].id,...snap.docs[0].data()};}
function renderProfile(){if(!profile)return;document.getElementById("profileName").textContent=profile.name||"Dispatcher";document.getElementById("profileArea").textContent=[profile.serviceArea,profile.vehicleType].filter(Boolean).join(" • ");const approved=profile.isApproved===true&&profile.isActive===true;document.getElementById("approvalStatus").textContent=profile.isApproved===true?(profile.isActive===true?"Approved":"Profile inactive"):"Awaiting admin approval";const btn=document.getElementById("availabilityBtn");btn.disabled=!approved;btn.textContent=profile.isAvailable===true?"I am AVAILABLE — tap to go offline":"I am unavailable — tap to go AVAILABLE";btn.className=`btn availabilityButton ${profile.isAvailable===true?'available':'unavailable'}`;document.getElementById("availabilityHelp").textContent=approved?"You can receive Biserry delivery requests while online.":"Biserry admin must approve your account before you can go live.";jobsCard.classList.toggle("hidden",!approved);}
function renderJobs(list){const el=document.getElementById("dispatcherJobs"),count=document.getElementById("dispatcherJobCount");const active=list.filter(x=>["Offered","Accepted","Picked Up","On the Way"].includes(x.status));count.textContent=String(active.length);el.innerHTML=active.length?active.map(j=>`<div class="jobCard"><strong>Order ${esc(j.orderId)}</strong><p>${esc(j.deliveryArea||"Delivery details become available after acceptance.")}</p><span class="statusPill">${esc(j.status)}</span><div class="jobActions">${j.status==="Offered"?`<button class="btn" onclick="acceptDispatchJob('${j.id}')" type="button">Accept</button><button class="btn outline" onclick="declineDispatchJob('${j.id}')" type="button">Decline</button>`:""}${j.status==="Accepted"?`<button class="btn" onclick="updateDispatchJob('${j.id}','Picked Up')" type="button">Picked Up</button>`:""}${j.status==="Picked Up"?`<button class="btn" onclick="updateDispatchJob('${j.id}','On the Way')" type="button">On the Way</button>`:""}${j.status==="On the Way"?`<button class="btn" onclick="updateDispatchJob('${j.id}','Delivered')" type="button">Delivered</button>`:""}</div></div>`).join(""):'<p class="formNote">No active delivery request.</p>';}
function watchJobs(){unsubscribeJobs?.();if(!profile?.id)return;const q=query(collection(db,"dispatchRequests"),where("dispatcherId","==",profile.id));unsubscribeJobs=onSnapshot(q,s=>renderJobs(s.docs.map(d=>({id:d.id,...d.data()}))),e=>console.warn("Dispatch request listener:",e));}
window.acceptDispatchJob=async id=>{try{const snap=await getDoc(doc(db,"dispatchRequests",id));if(!snap.exists())return;const j=snap.data();await updateDoc(doc(db,"dispatchRequests",id),{status:"Accepted",acceptedAt:serverTimestamp(),updatedAt:serverTimestamp()});await setDoc(doc(db,"orderTracking",j.orderId),{orderStatus:"Dispatcher Assigned",dispatchStatus:"Accepted",dispatcherName:profile.name||"Dispatcher",updatedAt:serverTimestamp()},{merge:true});await updateDoc(doc(db,"orders",j.orderId),{orderStatus:"Dispatcher Assigned",dispatchStatus:"Accepted",assignedDispatcherId:profile.id,assignedDispatcherName:profile.name||"Dispatcher",updatedAt:serverTimestamp()});}catch(e){alert("Could not accept request: "+e.message)}};
window.declineDispatchJob=async id=>{try{await updateDoc(doc(db,"dispatchRequests",id),{status:"Declined",updatedAt:serverTimestamp()});}catch(e){alert("Could not decline request: "+e.message)}};
window.updateDispatchJob=async(id,status)=>{try{const snap=await getDoc(doc(db,"dispatchRequests",id));if(!snap.exists())return;const j=snap.data();await updateDoc(doc(db,"dispatchRequests",id),{status,updatedAt:serverTimestamp(),...(status==="Delivered"?{deliveredAt:serverTimestamp()}:{})});const orderStatus=status==="Accepted"?"Dispatcher Assigned":status;await setDoc(doc(db,"orderTracking",j.orderId),{orderStatus,dispatchStatus:status,dispatcherName:profile.name||"Dispatcher",updatedAt:serverTimestamp()},{merge:true});await updateDoc(doc(db,"orders",j.orderId),{orderStatus,dispatchStatus:status,updatedAt:serverTimestamp()});}catch(e){alert("Could not update request: "+e.message)}};
loginForm.addEventListener("submit",async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,document.getElementById("loginEmail").value.trim(),document.getElementById("loginPassword").value);}catch(err){alert("Login failed: "+err.message)}});
registerForm.addEventListener("submit",async e=>{e.preventDefault();try{const cred=await createUserWithEmailAndPassword(auth,document.getElementById("registerEmail").value.trim().toLowerCase(),document.getElementById("registerPassword").value);const data={authUid:cred.user.uid,name:document.getElementById("registerName").value.trim(),phone:document.getElementById("registerPhone").value.trim(),email:cred.user.email,serviceArea:document.getElementById("registerArea").value.trim(),vehicleType:document.getElementById("registerVehicle").value.trim(),isApproved:false,isActive:true,isAvailable:false,isPublic:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const ref=await addDoc(collection(db,"dispatchers"),data);profile={id:ref.id,...data};authCard.classList.add("hidden");profileCard.classList.remove("hidden");renderProfile();alert("Registration submitted. Biserry admin must approve your dispatcher profile before you can go live.");}catch(err){alert("Registration failed: "+err.message)}});
document.getElementById("availabilityBtn").addEventListener("click",async()=>{if(!profile||profile.isApproved!==true||profile.isActive!==true)return;const next=profile.isAvailable!==true;await updateDoc(doc(db,"dispatchers",profile.id),{isAvailable:next,isPublic:next,lastAvailabilityAt:serverTimestamp(),updatedAt:serverTimestamp()});profile.isAvailable=next;profile.isPublic=next;renderProfile();});
document.getElementById("logoutDispatcherBtn").addEventListener("click",()=>signOut(auth));document.getElementById("showLoginBtn").addEventListener("click",()=>toggleForms(false));document.getElementById("showRegisterBtn").addEventListener("click",()=>toggleForms(true));
onAuthStateChanged(auth,async user=>{if(!user){unsubscribeJobs?.();profile=null;authCard.classList.remove("hidden");profileCard.classList.add("hidden");jobsCard.classList.add("hidden");return;}profile=await findProfile(user.uid);if(!profile){authCard.classList.remove("hidden");profileCard.classList.add("hidden");jobsCard.classList.add("hidden");return;}authCard.classList.add("hidden");profileCard.classList.remove("hidden");renderProfile();watchJobs();});
let deferredInstallPrompt=null;const installBtn=document.getElementById("installDispatcherBtn");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;installBtn?.classList.remove("hidden")});installBtn?.addEventListener("click",async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.classList.add("hidden")});window.addEventListener("appinstalled",()=>installBtn?.classList.add("hidden"));
